### ISSUE TITLE
tiny suggestion 

### ISSUE THREAD

**Issue by persianphilosopher** [PatrickLouys/professional-php-sample-code#1]
This is a tiny, tiny issue, but this should be "You _are_ logged in".  I mentioned it because after the login that I accidentally had logged out because of the past tense. I saw in the code that it was obviously not the case.

https://github.com/PatrickLouys/professional-php-sample-code/blob/a7e02c8580518c827a9db0b7ff5e4c47db92fa79/src/User/Presentation/LoginController.php#L62

I didn't do a PR because I have not (yet) bought the book and if the code in the book says "were logged in" then perhaps it should not be changed.  

In any case, thank you for your wonderful work.

**Comment by PatrickLouys** [comment]
Thanks for the feedback. I'll keep this open for now and will change it when I release an updated version of the book.

**Comment by alturic** [comment]
Do you plan on any updates to the book in the near future? I have the book, but was curious if it was a living thing or not.

**Comment by PatrickLouys** [comment]
Not in the near future, but when we get a new PHP version with significant changes (generics for example), then I'll definitely update it to include those and fix all the small things that people noticed.
