### ISSUE TITLE
Any elegant way to prevent the validation running twice ?

### ISSUE THREAD

**Issue by guitarbien** [PatrickLouys/professional-php-sample-code#2]
https://github.com/PatrickLouys/professional-php-sample-code/blob/a7e02c8580518c827a9db0b7ff5e4c47db92fa79/src/Submission/Presentation/SubmissionController.php#L64

Hi Patrick, 

The `SubmissionController` has to save the errors to the flashBag If the request was invalid, is there a elegant way to prevent the controller running validation logic twice ? (`hasValidationErrors()` and 
`getValidationErrors()`)

I am thinking about use static variable to keep the value :
```
static $errors = [];

if (count($errors) > 0) {
    return $errors;
}

// validation 
```
but  it's kind of cheating, for me :)

Or move `$flashBag->add( ... )` into the `SubmissionForm`, but I think that's a violation to the SRP ?

--
By the way, I read your book and follow the tutorial step by step, it's really SOLID!! I followed the [no-framework-tutorial](https://github.com/PatrickLouys/no-framework-tutorial) a year ago and felt it was really a nice practice help php developers update the old php concept. After I finish this book I'll review the code again, hope I can share more feedback. 

GOOD JOB.

**Comment by PatrickLouys** [comment]
You could trigger the validation in the constructor and then store the error messages in the object (but not static). Or just get the error messages once.

```php
$form = $this->submissionFormFactory->createFromRequest($request);
$errors = $form->getValidationErrors();
if (count($errors) > 0) {
    foreach ($errors ...) {}
}
```
