### ISSUE TITLE
Is this meant to be __toString() ?

### ISSUE THREAD

**Issue by ajogden** [PatrickLouys/professional-php-sample-code#3]
https://github.com/PatrickLouys/professional-php-sample-code/blob/a7e02c8580518c827a9db0b7ff5e4c47db92fa79/src/Framework/Dbal/DatabaseUrl.php#L14

Hi

Loving the book, but I got errors saying DatabaseUrl class could not be cast to a string on the Doctrine migrations part, think this may need to be __toString().   Changed and it worked for me.

Regards

Anthony.

**Comment by PatrickLouys** [comment]
Did you call the `toString()` method here?

https://github.com/PatrickLouys/professional-php-sample-code/blob/a7e02c8580518c827a9db0b7ff5e4c47db92fa79/src/Framework/Dbal/ConnectionFactory.php#L18-L24
