### ISSUE TITLE
how can store them in the database?

### ISSUE THREAD

**Issue by mxj333** [PatrickLouys/professional-php-sample-code#5]
In  Checking for a permission  

Because we have only one role at the moment, the right approach is to hardcode it. If you decide to add another role, you can store them in the database and retrieve the roles of a user before you return an authenticated user.

how can store them in the database?
I'm a novice.
Thank you

**Comment by PatrickLouys** [comment]
In the same way that we stored the submissions.

The book is not really meant for a novice. Intermediate PHP knowledge is assumed. If you don't know how to store things in the database, start with some tutorials that go over this.

Cheers,
Patrick
