### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by mjlandicho** [PatrickLouys/professional-php-sample-code#9]
I`m stuck on your tutorial in sql injection. I followed what the book said but i getting error in my controller
Please help.
![Capture](https://user-images.githubusercontent.com/29293778/60691799-e0b2a380-9f04-11e9-9803-a2192cffcc3c.PNG)

**Comment by ellisgl** [comment]
Is the property submitLinkHandler set up?

**Comment by Ji20on** [comment]
> Is the property submitLinkHandler set up?

Yes, Im following the book, and then i encounter that. i compare my code to what the book said and it is the same.  I don`t know why.

**Comment by mjlandicho** [comment]
> > Is the property submitLinkHandler set up?
> 
> Yes, Im following the book, and then i encounter that. i compare my code to what the book said and it is the same. I don`t know why that error appear. this is my code.

> ![Capture](https://user-images.githubusercontent.com/29293778/60697074-12cf0000-9f1b-11e9-9ff8-e21c770cb3c9.PNG)

**Comment by ellisgl** [comment]
@Ji20on I take it you found the issue, which look like your constructor not having having the argument for the submitLinkHandler?
